name: Run API UI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #manual run
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        
    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2
      
    # install dependencies
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # execute gradle task
    - name: Run cucumber API Test
      run: ./gradlew cucumberApiTest
        
    - name: Run Cucumber Web Tests
      run: ./gradlew cucumberWebTest

    # upload the reports
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-reports
        path: build/reports/cucumber/
        

        

  
